spring:
  datasource:
    url: jdbc:postgresql://db:5432/ecommerce_crud_db
    username: lucasdenipotti
    password: teamviewer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /v3/swagger-ui.html

logging:
  level:
    org.springframework: INFO
    com.teamviewer.challenge.ecommerce: INFO